[package]
name = "zkcir"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan = "0.11.1"
lazy_static = "1.4.0"
pretty_assertions = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
