[package]
name = "zkcir-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zkcir"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
indicatif = "0.17.7"
tempfile = "3.8.1"
toml = "0.8.6"
walkdir = "2.4.0"
zkcir = { version = "0.1.0", path = "../zkcir" }
